### ISSUE TITLE
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated

### ISSUE THREAD

**Issue by shashibioinfo143** [iqbal-lab-org/Mykrobe_tb_workflow#4]
Dear Michael,

im getting error of **YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated** 
MissingInputException in line 15 of /home/fmr/Mykrobe_tb_workflow-master/rules/porechop.smk:
Missing input files for rule porechop:
data/basecalled/Test_15.fastq.gz
if you can please help me to resolve this issue asap.

thank you
![snakemake](https://user-images.githubusercontent.com/54669756/66919173-75698900-f03e-11e9-9794-6937789d3908.png)

**Comment by mbhall88** [comment]
Hi @shashibioinfo143 

The YAML message is just a warning - it isn't the cause of the error.

The error (in red text) says it can't find your input file `data/basecalled/Test_15.fastq.gz`

Does that file exist inside that directory? `ls data/basecalled`

(For future log/errors could you please just paste the output directly from your terminal rather than a screenshot)

**Comment by shashibioinfo143** [comment]
Hi Michael,
Yes the file was there data/basecalled folder as Test_15_pass.fastq.gz
but filename i just typed as Test_15 instead of Test_15_pass in config file. that is the reason for Error.
the error was resolved and Process is running.
i regret to post this issue for this simple error
Thank you

**Comment by mbhall88** [comment]
No problems @shashibioinfo143. Glad it is all working now. Let me know if you have any further issues.

**Comment by shashibioinfo143** [comment]
> No problems @shashibioinfo143. Glad it is all working now. Let me know if you have any further issues.

Thanks a lot
